export const SCHEMA_VERSION = "1" as const;

export const SCHEMA_IDS = {
  primitives: "urn:archflow:schema:v1:primitives",
  phaseInstance: "urn:archflow:schema:v1:phase-instance",
  workflow: "urn:archflow:schema:v1:workflow",
  config: "urn:archflow:schema:v1:config",
  rubric: "urn:archflow:schema:v1:rubric",
  constitutionRule: "urn:archflow:schema:v1:constitution-rule",
  review: "urn:archflow:schema:v1:review",
  reviewEvidence: "urn:archflow:schema:v1:review-evidence",
  adjudication: "urn:archflow:schema:v1:adjudication",
  adjudicationEvidence: "urn:archflow:schema:v1:adjudication-evidence",
  evidenceSlots: "urn:archflow:schema:v1:evidence-slots",
  triage: "urn:archflow:schema:v1:triage",
  supplementalReview: "urn:archflow:schema:v1:supplemental-review",
  supplementalReviewRecord: "urn:archflow:schema:v1:supplemental-review-record",
  gateContract: "urn:archflow:schema:v1:gate-contract",
  gateDecision: "urn:archflow:schema:v1:gate-decision",
  gateRequest: "urn:archflow:schema:v1:gate-request",
  gateDecisionRecord: "urn:archflow:schema:v1:gate-decision-record",
  activeGate: "urn:archflow:schema:v1:active-gate",
  projectError: "urn:archflow:schema:v1:project-error",
  protocolError: "urn:archflow:schema:v1:protocol-error",
  mcpTools: "https://archflow.dev/schemas/v1/mcp-tools",
  resultExpectation: "https://archflow.dev/schemas/v1/result-expectation",
  pathClaim: "urn:archflow:schema:v1:path-claim",
  releaseManifest: "urn:archflow:schema:v1:release-manifest",
  secretScanResult: "urn:archflow:schema:v1:secret-scan-result",
  durablePrimitives: "urn:archflow:schema:v1:durable-primitives",
  taskState: "urn:archflow:schema:v1:task-state",
  intentReceipt: "urn:archflow:schema:v1:intent-receipt",
  taskInitialization: "urn:archflow:schema:v1:task-initialization",
  legacyImportInitialization: "urn:archflow:schema:v1:legacy-import-initialization",
  documentArtifact: "urn:archflow:schema:v1:document-artifact",
  implementationOutput: "urn:archflow:schema:v1:implementation-output",
  resultManifest: "urn:archflow:schema:v1:result-manifest"
} as const;
