import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { parseAdjudicationEvidence, parseAndDeriveAdjudication, parseReferencedAdjudicationEvidence } from "../../src/contracts/adjudication.js";

const valid = async () => JSON.parse(await readFile(new URL("../fixtures/contracts/adjudication/valid.json", import.meta.url), "utf8")) as Record<string, unknown>;
describe("adjudication semantics", () => {
  it("derives independent constitution, drift, and trigger summaries", async () => { const value = await valid(); const before = structuredClone(value); expect(parseAndDeriveAdjudication(value).constitution).toBe("pass"); expect(value).toEqual(before); expect(() => parseAndDeriveAdjudication({ ...value, drift: "material" })).toThrow(/drift must be aligned/); });
  it("cannot upgrade missing, stale, failed, unknown, or mismatched evidence to compliance", async () => { for (const state of ["missing", "stale", "unknown", "failed", "digest-mismatch"]) { const value = await valid(); const finding = structuredClone((value.rule_findings as Array<Record<string, unknown>>)[0]!); finding.enforced_by = [{ mechanism: "path-contract", state, details: "Not current.", ...(state === "stale" ? { subject_digest: "0".repeat(64), evidence_digest: "f".repeat(64) } : {}) }]; expect(() => parseAndDeriveAdjudication({ ...value, rule_findings: [finding] })).toThrow(); } });
  it("rejects trigger list and current-subject contradictions", async () => { const value = await valid(); expect(() => parseAndDeriveAdjudication({ ...value, matched_rule_versions: [{ rule_id: "safe-paths", rule_version: 2 }] })).toThrow(/contradict/); const finding = structuredClone((value.rule_findings as Array<Record<string, unknown>>)[0]!); (finding.enforced_by as Array<Record<string, unknown>>)[0]!.subject_digest = "0".repeat(64); expect(() => parseAndDeriveAdjudication({ ...value, rule_findings: [finding] })).toThrow(/wrong subject/); });
  it("allows an empty pass evidence list but requires every supplied entry to be current and subject-bound", async () => { const value = await valid(); const finding = structuredClone((value.rule_findings as Array<Record<string, unknown>>)[0]!); finding.enforced_by = []; expect(parseAndDeriveAdjudication({ ...value, rule_findings: [finding] }).rule_findings[0]?.enforced_by).toEqual([]); finding.enforced_by = [structuredClone(((value.rule_findings as Array<Record<string, unknown>>)[0]!.enforced_by as unknown[])[0]), { mechanism: "manual-check", state: "unknown", details: "Not current." }]; expect(() => parseAndDeriveAdjudication({ ...value, rule_findings: [finding] })).toThrow(/suspect mechanical evidence/); });
  it("composes provenance and reference parsers through empty-list pass semantics", async () => { const value = await valid(); const finding = structuredClone((value.rule_findings as Array<Record<string, unknown>>)[0]!); finding.enforced_by = []; const evidence = { ...value, rule_findings: [finding], assurance: "agent-declared", model_family: "unknown", model: "unknown", effort: "unknown" }; expect(parseAdjudicationEvidence(evidence).rule_findings[0]?.enforced_by).toEqual([]); expect(parseReferencedAdjudicationEvidence({ evidence_digest: "f".repeat(64), evidence }).evidence.rule_findings[0]?.enforced_by).toEqual([]); });
});
