import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { parseAndDeriveReview, parseReferencedReviewEvidence, parseReviewEvidence } from "../../src/contracts/review.js";

const fixture = async (name: string) => JSON.parse(await readFile(new URL(`../fixtures/contracts/review/${name}`, import.meta.url), "utf8")) as unknown;
describe("review semantics", () => {
  it("checks exact verdict and count without mutating raw claims", async () => { const value = await fixture("valid.json"); const invalid = await fixture("invalid-contradiction.json"); const before = structuredClone(value); expect(parseAndDeriveReview(value).verdict).toBe("fail"); expect(value).toEqual(before); expect(() => parseAndDeriveReview(invalid)).toThrow(/blocking_count/); });
  it("keeps provenance variants closed and disallows server-attested self-review", async () => { const review = await fixture("valid.json") as Record<string, unknown>; const declared = { ...review, assurance: "agent-declared", model_family: "unknown", model: "unknown", effort: "unknown" }; expect(parseReviewEvidence(declared).assurance).toBe("agent-declared"); expect(() => parseReviewEvidence({ ...declared, adapter: "codex-cli" })).toThrow(); expect(() => parseReviewEvidence({ ...declared, assurance: "server-attested", adapter: "codex-cli", cli_version: "1", model_family: "codex", model: "gpt", effort: "high", invocation_id: "invocation-1", envelope_input_digest: "d".repeat(64), observed_output_digest: "e".repeat(64), result_id: "result-1", role: "self-review", step: "self_review" })).toThrow(/server-attested/); });
  it("composes evidence and referenced-evidence parsing through all raw semantics", async () => { const review = await fixture("valid.json") as Record<string, unknown>; const declared = { ...review, assurance: "agent-declared", model_family: "unknown", model: "unknown", effort: "unknown" }; const duplicate = { ...declared, findings: [...(review.findings as unknown[]), ...(review.findings as unknown[])] }; expect(() => parseReviewEvidence(duplicate)).toThrow(/duplicate finding_id/); expect(() => parseReferencedReviewEvidence({ evidence_digest: "d".repeat(64), evidence: duplicate })).toThrow(/duplicate finding_id/); expect(() => parseReviewEvidence({ ...declared, verdict: "pass" })).toThrow(/verdict/); expect(() => parseReviewEvidence({ ...declared, role: "self-review", step: "counter_review" })).toThrow(/self-review role/); });
});
